# Generated by Django 5.2.6 on 2025-09-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_task_created_by_alter_task_priority_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
