# Generated by Django 5.2.6 on 2025-09-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0004_rename_text_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date', 'priority'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
