# Generated by Django 5.2.6 on 2025-09-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['title'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
    ]
